import { loadDeposits } from './../../../../../store/deposit/deposit.actions';
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { Contract } from 'src/app/store/contract/contract.model';
import { Deposit } from 'src/app/store/deposit/deposit.model';

import { TrancheFirestoreService } from 'src/app/services/tranche-firestore.service';
import { DepositFirestoreService } from 'src/app/services/deposit-firestore.service';

import { DepositFacade } from 'src/app/store/deposit/deposit.facade';
import { TrancheFacade } from 'src/app/store/tranche/tranche.facade';
import { Tranche } from 'src/app/store/tranche/tranche.model';
import { Observable, tap } from 'rxjs';


@Component({
	selector: 'app-contract-info',
	standalone: true,
	templateUrl: './contract-info.component.html',
	styleUrls: ['./contract-info.component.scss'],
	imports: [
		CommonModule,
		IonicModule
	],
})
export class ContractInfoComponent implements OnInit {

	@Input() contract!: Contract;

	tranches$: Observable<Tranche[]> = this.trancheFacade.tranches$.pipe(
		tap(tranches => {
			console.log('Tranches loaded in ContractInfoComponent:', tranches);
			if (tranches && tranches.length > 0) {
				this.loadDeposits(tranches[0].uid);
			}
		})
	);

	deposits$: Observable<Deposit[]> = this.depositFacade.deposits$;

	constructor(
		private trancheService: TrancheFirestoreService,
		private depositService: DepositFirestoreService,
		private depositFacade: DepositFacade,
		private trancheFacade: TrancheFacade
	) {}

	ngOnInit() {
		// Load tranches or any other necessary data here if needed
		this.trancheFacade.loadTranches(this.contract?.uid || '');
	}

	loadDeposits(trancheUid: string) {
		this.depositFacade.loadDeposits(trancheUid);
	}

	deposit(tranche) {
		
		// Create a new deposit object
		const newDeposit: Deposit = {
			contractUid: this.contract.uid,
			trancheUid: tranche.uid,
			amount: 50000, // Example amount, replace with actual value
			depositedAt: Date.now(),
			uid: '' // This will be generated by Firestore
		};

		// Call the service to create the deposit
		this.depositFacade.createDeposit(newDeposit);
	}

}