import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';

import { Observable, tap } from 'rxjs';

import { Contract } from 'src/app/store/contract/contract.model';
import { Deposit } from 'src/app/store/deposit/deposit.model';
import { Tranche } from 'src/app/store/tranche/tranche.model';
import { CommissionPayment } from 'src/app/store/commission-payment/commission-payment.model';

import { DepositFacade } from 'src/app/store/deposit/deposit.facade';
import { TrancheFacade } from 'src/app/store/tranche/tranche.facade';
import { CommissionPaymentFacade } from 'src/app/store/commission-payment/commission-payment.facade';
import { AdvisorFacade } from 'src/app/store/advisor/advisor.facade';

@Component({
	selector: 'app-contract-info',
	standalone: true,
	templateUrl: './contract-info.component.html',
	styleUrls: ['./contract-info.component.scss'],
	imports: [
		CommonModule,
		IonicModule
	],
})
export class ContractInfoComponent implements OnInit {

	@Input() contract!: Contract;

	tranches$: Observable<Tranche[]> = this.trancheFacade.tranches$.pipe(
		tap(tranches => {
			if (tranches && tranches.length > 0) {
				this.loadData(tranches[0].uid);
			}
		})
	);

	deposits$: Observable<Deposit[]> = this.depositFacade.deposits$;

	commissionPayments$: Observable<CommissionPayment[]> = this.commissionPaymentFacade.commissionPayments$;

	advisorsDic$ = this.advisorFacade.entities$;

	constructor(
		private depositFacade: DepositFacade,
		private trancheFacade: TrancheFacade,
		private advisorFacade: AdvisorFacade,
		private commissionPaymentFacade: CommissionPaymentFacade,
	) {}

	ngOnInit() {
		// Load tranches or any other necessary data here if needed
		this.trancheFacade.loadTranches(this.contract?.uid || '');
	}

	loadData(trancheUid: string) {
		this.depositFacade.loadDeposits(trancheUid);
		this.commissionPaymentFacade.loadCommissionPayments(trancheUid);
	}

	createTranche() {
		this.trancheFacade.createTranche(this.contract.uid, 100000);
	}

	deposit(tranche) {
		
		// Create a new deposit object
		const newDeposit: Deposit = {
			contractUid: this.contract.uid,
			trancheUid: tranche.uid,
			amount: 50000, // Example amount, replace with actual value
			depositedAt: Date.now(),
			uid: '' // This will be generated by Firestore
		};

		// Call the service to create the deposit
		this.depositFacade.createDeposit(newDeposit);
	}

}